repos:
-   repo: local
    hooks:
    -   id: black
        name: black
        entry: black
        types:
            - python
        language: python
    -   id: isort
        name: isort
        entry: isort
        language: python