services:
  api:
    build:
      context: .
    container_name: secret-app
    environment:
      DATABASE_URL: "mongodb://kiruha:example@mongo_db:27017/"
    ports:
      - '8080:80'
    restart: "no"
    depends_on:
      mongo_db:
        condition: service_started

  mongo_db:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: kiruha
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - "mongo_db_data:/var/lib/mongo/data"

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: kiruha
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://kiruha:example@mongo_db:27017/
      ME_CONFIG_BASICAUTH: false

  test_mongo_db:
    image: mongo
    restart: always
    ports:
      - 27018:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: kiruha
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - "test_mongo_db_data:/var/lib/mongo/test_data"

volumes:
  mongo_db_data:
  test_mongo_db_data: