on:
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12"]

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        pwd
        ls -l
        
    - name: Install dependencies
      run: |
        python -m pip install poetry
        python -m poetry install
    
    - name: Docker Compose
      uses: hoverkraft-tech/compose-action@v2.0.1
      with:
        compose-file: ./docker-compose.yaml
    
    - name: Lint with flake8
      run: |
        python -m poetry run pylint -rn ./app
    
    - name: Test with pytest
      run: |
        python -m poetry run pytest

